version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - OPENWEATHERMAP_API_KEY=your_api_key_here
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
#    volumes:
#      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
